---
kind: pipeline
name: release

steps:
  - name: build & push release image
    image: thegeeklab/drone-docker-buildx:24.1@sha256:ec22bdd258013478e6c5cb20430a7ea815d9f3e12ac71ee90a66c1b1d74071e5
    settings:
      auto_tag: true
      repo: mazzolino/restic
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    exclude:
      - pull_request
  branch:
    - master

---
kind: pipeline
name: pr

steps:
  - name: test
    image: mazzolino/docker-shellspec
    volumes:
      - name: dockersock
        path: /var/run

  - name: build & push PR image
    image: thegeeklab/drone-docker-buildx:24.1@sha256:ec22bdd258013478e6c5cb20430a7ea815d9f3e12ac71ee90a66c1b1d74071e5
    settings:
      repo: mazzolino/restic
      tags:
        - pr-${DRONE_PULL_REQUEST}
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/armhf
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - pull_request

services:
    - name: docker
      image: docker:20.10-dind
      commands:
        - dockerd
      privileged: true
      volumes:
        - name: dockersock
          path: /var/run

volumes:
  - name: dockersock
    temp: {}
---
kind: signature
hmac: d91abcde2378ecd38a703fe1770b707842309ba47ea3844ff12b7a47440551d0

...
