#!/bin/bash
set -euo pipefail

function run_commands {
  COMMANDS=$1
  RESULT=0
  while IFS= read -r cmd; do
    echo "$cmd" && eval "$cmd"
    if [ $? -ne 0 ]; then
      RESULT=1
    fi
  done < <(printf '%s\n' "$COMMANDS")
  return $RESULT
}

function run_exit_commands {
	set +e
	set +o pipefail
	run_commands "${POST_COMMANDS_EXIT:-}"
}

main() {
  set +e
  run_commands "${PRE_COMMANDS:-}"
  pre_result=$?
  set -e
  if [ $pre_result -ne 0 ]; then
    echo "Warning: At least one command of PRE_COMMANDS exited with a non-zero exit code."
    run_commands "${PRE_COMMANDS_FAILURE:-}"

    if [ "${ABORT_ON_PRE_COMMANDS_FAILURE:-}" == "true" ]; then
      exit 1
    fi
  fi

  repo_arg="--repo=${RESTIC_REPOSITORY}"
  if [ -n "${RESTIC_REPOSITORY_FILE:-}" ]; then
    echo Using restic repository file at $RESTIC_REPOSITORY_FILE
    repo_arg="--repository-file=${RESTIC_REPOSITORY_FILE}"
    unset RESTIC_REPOSITORY
  fi

  start=$(date +%s)

  if [ -n "${RESTIC_FORGET_ARGS:-}" ]; then
    echo Forget about old snapshots based on RESTIC_FORGET_ARGS = ${RESTIC_FORGET_ARGS}
    restic forget ${RESTIC_FORGET_ARGS}
  fi

  echo Starting prune at "$(date +"%Y-%m-%d %H:%M:%S")"

  set +e
  if ! restic "${repo_arg}" prune ${RESTIC_PRUNE_ARGS:-}; then
    set -e
    run_commands "${POST_COMMANDS_FAILURE:-}"
    exit
  else
    set -e
  fi

  echo Prune successful

  end="$(date +%s)"
  echo Finished prune at "$(date +"%Y-%m-%d %H:%M:%S")" after $((end-start)) seconds

  run_commands "${POST_COMMANDS_SUCCESS:-}"
}

trap run_exit_commands EXIT
main "$@"
